name:                redka
version:             0.1.0.0
github:              paulrzcz/redka
license:             BSD-3-Clause
author:              Pavel Ryzhov
maintainer:          paul@paulrz.cz
copyright:           2024 (c) Pavel Ryzhov

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/paulrzcz/redka#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- network
- bytestring
- stm
- stm-hamt
- stm-containers
- scanner

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  redka-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - redka
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  redka-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - redka
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
